"""Orchestration entrypoints for EchoMind -> TRIBE smoke-test inference runs."""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

from echomind.cues.contracts import CueDeliveryMode, InferenceResultSummary, StimulusManifest
from echomind.media.renderer import render_demo_planner_outputs
from echomind.tribe.aggregates import build_inference_summary
from echomind.tribe.client import StubTribeClient, TribeClient, TribeRawOutput
from echomind.tribe.io import TribeRunArtifacts, save_tribe_run_artifacts
from echomind.tribe.preprocess import TribeBatchInput, preprocess_manifest_for_tribe


@dataclass(slots=True)
class TribeInferenceRunResult:
    """Collected outputs for one TRIBE integration run."""

    batch_input: TribeBatchInput
    raw_outputs: list[TribeRawOutput]
    summary: InferenceResultSummary
    artifacts: TribeRunArtifacts


def run_tribe_inference(
    manifest: StimulusManifest,
    request_id: str,
    artifact_root: str | Path = "artifacts/inference",
    engine_name: str = "tribe-v2",
    client: TribeClient | None = None,
    supported_modalities: set[CueDeliveryMode] | None = None,
) -> TribeInferenceRunResult:
    """Run one deterministic TRIBE integration path and persist outputs."""

    batch_input = preprocess_manifest_for_tribe(
        manifest=manifest,
        request_id=request_id,
        engine_name=engine_name,
        supported_modalities=supported_modalities,
    )

    resolved_client = client or StubTribeClient()
    raw_outputs = resolved_client.infer_batch(batch_input.stimuli)

    summary = build_inference_summary(
        request_id=request_id,
        engine_name=engine_name,
        outputs=raw_outputs,
        notes="Simulation-only inference summary generated by EchoMind TRIBE integration layer.",
    )

    artifacts = save_tribe_run_artifacts(
        artifact_root=artifact_root,
        request_id=request_id,
        request_payload=batch_input.model_dump(mode="json"),
        raw_outputs=raw_outputs,
        summary=summary,
    )
    summary.summary_metadata.update(
        {
            "run_dir": str(artifacts.run_dir),
            "raw_outputs_path": str(artifacts.raw_outputs_path),
        }
    )

    return TribeInferenceRunResult(
        batch_input=batch_input,
        raw_outputs=raw_outputs,
        summary=summary,
        artifacts=artifacts,
    )


def run_demo_text_only_smoke_inference(
    artifact_root: str | Path = "artifacts/inference",
) -> TribeInferenceRunResult:
    """Run demo planner+renderer outputs through text-only TRIBE smoke path."""

    root = Path(artifact_root)
    media_root = root / "media"
    manifest = render_demo_planner_outputs(artifact_root=media_root)
    return run_tribe_inference(
        manifest=manifest,
        request_id="smoke-demo-text-only",
        artifact_root=root,
        supported_modalities={CueDeliveryMode.TEXT_ONLY},
    )
